In [10]:
from backend.trips_data import TripData
from backend.connect_to_api import ResRobot

resrobot = ResRobot()
resrobot.access_id_from_location("malmö")

Name                                               extId
MALMÖ                                              740098548
Malmö Centralstation                               740000003
Malmö Triangeln station                            740001587
Malmö Hyllie station                               740001586
Malmö Svågertorp station                           740001546
Malmö Persborg station                             740001486
Malmö Rosengård station                            740001621
Malmö Östervärn station                            740001483
Malmö Fosieby station                              740001553
Malmö C Norra Vallgatan                            740072050

In [11]:
resrobot.access_id_from_location("göteborg")

Name                                               extId
GÖTEBORG                                           740098001
Göteborg Centralstation                            740000002
Göteborg Sävenäs lokstation                        740016365
GÖTEBORG GAMLESTADEN                               740098526
Göteborg Korsvägen                                 740015578
Göteborg Kungsportsplatsen                         740016358
Göteborg Stenpiren                                 740072430
Göteborg Eketrägatan                               740025624
Göteborg Vårväderstorget                           740025707
Göteborg Axel Dahlströms torg                      740025608

In [12]:
resrobot.access_id_from_location("Umeå")

Name                                               extId
UMEÅ                                               740098065
Umeå Centralstation                                740000190
Umeå Busstation                                    740020461
Umeå Östra station                                 740001581
Umeå Vasaplan                                      740020116
Umeå Airport                                       740025159
Umeå Ålidhem centrum                               740023156
Umeå Ålidhöjd                                      740045439
Umeå Älvans väg                                    740045410
Umeå Alviksgränd                                   740045280

In [13]:
ids = {"MALMÖ": 740000003, "GÖTEBORG": 740000002, "UMEÅ": 740000190}

trip_data = TripData(origin_id=ids["MALMÖ"], destination_id=ids["GÖTEBORG"])

trip_data.number_trips

5

In [14]:
trip_data.next_available_trip()

,name,extId,lon,lat,depTime,depDate,arrTime,arrDate,time,date
0,Malmö Centralstation,740000003,13.000910,55.609456,11:10:00,2025-01-12,NaN,NaN,11:10:00,2025-01-12
1,Snapparp E6 Circle K (Laholm kn),740020782,12.969798,56.541206,12:28:00,2025-01-12,12:28:00,2025-01-12,12:28:00,2025-01-12
2,Halmstad C Resecentrum,740043449,12.865811,56.670273,12:50:00,2025-01-12,12:45:00,2025-01-12,12:45:00,2025-01-12
3,Göteborg Nils Ericsonterminal,740020483,11.971852,57.710271,NaN,NaN,14:30:00,2025-01-12,14:30:00,2025-01-12

In [17]:
trip_data = TripData(origin_id=ids["MALMÖ"], destination_id=ids["UMEÅ"])
trip_data.next_available_trip()

,name,extId,lon,lat,depTime,depDate,arrTime,arrDate,time,date
0,Malmö Centralstation,740000003,13.000910,55.609456,11:07:00,2025-01-12,NaN,NaN,11:07:00,2025-01-12
1,Lund Centralstation,740000120,13.186897,55.708094,11:20:00,2025-01-12,NaN,NaN,11:20:00,2025-01-12
2,Hässleholm Centralstation,740000006,13.763141,56.157762,11:48:00,2025-01-12,11:47:00,2025-01-12,11:47:00,2025-01-12
3,Alvesta station,740000004,14.556322,56.898778,12:29:00,2025-01-12,12:27:00,2025-01-12,12:27:00,2025-01-12
4,Nässjö Centralstation,740000140,14.693983,57.652443,13:02:00,2025-01-12,13:01:00,2025-01-12,13:01:00,2025-01-12
5,Mjölby station,740000180,15.131992,58.322984,13:39:00,2025-01-12,13:38:00,2025-01-12,13:38:00,2025-01-12
6,Linköping Centralstation,740000009,15.624960,58.416634,13:56:00,2025-01-12,13:54:00,2025-01-12,13:54:00,2025-01-12
7,Norrköping Centralstation,740000007,16.183343,58.596625,14:19:00,2025-01-12,14:18:00,2025-01-12,14:18:00,2025-01-12
8,Stockholm Centralstation,740000001,18.058151,59.330136,NaN,NaN,15:31:00,2025-01-12,15:31:00,2025-01-12
9,Stockholm Centralstation,740000001,18.058151,59.330136,16:23:00,2025-01-12,NaN,NaN,16:23:00,2025-01-12
10,Arlanda Centralstation (Sigtuna kn),740000556,17.929201,59.649469,16:42:00,2025-01-12,NaN,NaN,16:42:00,2025-01-12
11,Uppsala Centralstation,740000005,17.646086,59.858531,17:00:00,2025-01-12,NaN,NaN,17:00:00,2025-01-12
12,Gävle Centralstation,740000210,17.151221,60.676118,17:45:00,2025-01-12,17:43:00,2025-01-12,17:43:00,2025-01-12
13,Söderhamn station,740000154,17.035682,61.299600,18:30:00,2025-01-12,18:30:00,2025-01-12,18:30:00,2025-01-12
14,Hudiksvall station,740000187,17.109034,61.724494,18:58:00,2025-01-12,18:58:00,2025-01-12,18:58:00,2025-01-12
15,Sundsvall Centralstation,740000130,17.315633,62.386873,NaN,NaN,19:53:00,2025-01-12,19:53:00,2025-01-12
16,Sundsvall Centralstation,740000130,17.315633,62.386873,20:15:00,2025-01-12,NaN,NaN,20:15:00,2025-01-12
17,Sundsvall Västra station,740020045,17.291668,62.389893,20:20:00,2025-01-12,NaN,NaN,20:20:00,2025-01-12
18,Timrå station,740000242,17.330546,62.486392,20:35:00,2025-01-12,20:35:00,2025-01-12,20:35:00,2025-01-12
19,Härnösand station,740000253,17.928635,62.635182,21:11:00,2025-01-12,21:10:00,2025-01-12,21:10:00,2025-01-12
20,Kramfors station,740000220,17.778182,62.929111,21:34:00,2025-01-12,21:33:00,2025-01-12,21:33:00,2025-01-12
21,Örnsköldsvik Centralstation,740001570,18.704305,63.289282,22:16:00,2025-01-12,22:16:00,2025-01-12,22:16:00,2025-01-12
22,Örnsköldsvik Norra station,740001569,18.716108,63.303035,22:21:00,2025-01-12,22:21:00,2025-01-12,22:21:00,2025-01-12
23,Husum station (Örnsköldsvik kn),740001584,19.155725,63.343909,22:37:00,2025-01-12,22:37:00,2025-01-12,22:37:00,2025-01-12
24,Nordmaling Resecentrum/Station (Nordmaling-AC kn),740001583,19.486285,63.578303,22:52:00,2025-01-12,22:52:00,2025-01-12,22:52:00,2025-01-12
25,Hörnefors Resecentrum/Station (Umeå kn),740001582,19.908464,63.632661,23:03:00,2025-01-12,23:03:00,2025-01-12,23:03:00,2025-01-12
26,Umeå Östra station,740001581,20.293454,63.817659,NaN,NaN,23:20:00,2025-01-12,23:20:00,2025-01-12
27,Umeå Centralstation,740000190,20.266810,63.830064,NaN,NaN,23:25:00,2025-01-12,23:25:00,2025-01-12